config/routes.rb
Netwurking::Application.routes.draw do
  resources :friendships

  devise_for :users

  get "home/index"

  resources :bizcards
  resources :users

  root :to => 'home#index'

end

app/models/bizcard.rb
class Bizcard < ActiveRecord::Base
  has_many :relationships
  has_many :users, :through => :relationships
  
  attr_accessible :name, :bizname, :user_id
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
  attr_accessible :friend_id, :user_id
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :bizcard
  
  attr_accessible :bizcard_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friendships
  has_many :friends, :through => :friendships, :dependent => :destroy
  has_many :relationships
  has_many :bizcards, :through => :relationships, :dependent => :destroy
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :full_name, :cardbackground, :twitter, :company, :cardbackgroundimage, :token, :address, :address2, :city, :state, :zip, :country, :title

  before_create :generate_token

  protected

  def generate_token
    begin
      token = SecureRandom.hex(3)
    end while User.where(:token => token).exists?
    self.token = token
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bizcards_controller.rb
class BizcardsController < ApplicationController
  # GET /bizcards
  # GET /bizcards.json
  def index
    @bizcards = Bizcard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bizcards }
    end
  end

  # GET /bizcards/1
  # GET /bizcards/1.json
  def show
    @bizcard = Bizcard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bizcard }
    end
  end

  # GET /bizcards/new
  # GET /bizcards/new.json
  def new
    @bizcard = Bizcard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bizcard }
    end
  end

  # GET /bizcards/1/edit
  def edit
    @bizcard = Bizcard.find(params[:id])
  end

  # POST /bizcards
  # POST /bizcards.json
  def create
    @bizcard = Bizcard.new(params[:bizcard])
    @bizcard.relationships.build(:user_id => current_user.id)

    respond_to do |format|
      if @bizcard.save
        format.html { redirect_to root_path, notice: 'Bizcard was successfully created.' }
        format.json { render json: @bizcard, status: :created, location: @bizcard }
      else
        format.html { render action: "new" }
        format.json { render json: @bizcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bizcards/1
  # PUT /bizcards/1.json
  def update
    @bizcard = Bizcard.find(params[:id])

    respond_to do |format|
      if @bizcard.update_attributes(params[:bizcard])
        format.html { redirect_to @bizcard, notice: 'Bizcard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bizcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bizcards/1
  # DELETE /bizcards/1.json
  def destroy
    @bizcard = Bizcard.find(params[:id])
    @bizcard.destroy

    respond_to do |format|
      format.html { redirect_to bizcards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to root_url, notice: 'This card has been added to your stack' }
        format.json { render json: @friendship, status: :created, location: @friendship }
      else
        format.html { render action: "new" }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: 'This card has been removed from your stack' }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
    @search = User.search(params[:q])
    @users = @search.result
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @search = User.search(params[:q])
    @users = @search.result


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  
  def update
    @user = User.find params[:id]

    respond_to do |format|
      if @user.update_attributes(params[:user])
        
        format.html { redirect_to(edit_user_path(current_user), :notice => 'User was successfully updated.') }
        format.json { respond_with_bip(@user) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@user) }
      end
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bizcards_helper.rb
module BizcardsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bizcards/_form.html.erb
<%= form_for(Bizcard.new) do |f| %>
  <% if Bizcard.new.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bizcard.errors.count, "error") %> prohibited this bizcard from being saved:</h2>

      <ul>
      <% @bizcard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<div class="bizcardformwrapper">
<div class="bizcardformtitle">		
Name:
</div>
<%= f.text_field :name, :class => "nameedit", :placeholder => "First & Last" %>

<div class="bizcardformtitle">	
<br>	
Company:
</div>
<%= f.text_field :bizname, :class => "nameedit", :placeholder => "Co. Name" %>

<div class="actions">
<%= f.submit "Add Card", :class => "submitbutton"  %>
</div>
</div>

<% end %>

app/views/bizcards/edit.html.erb
<h1>Editing bizcard</h1>

<%= render 'form' %>

<%= link_to 'Show', @bizcard %> |
<%= link_to 'Back', bizcards_path %>

app/views/bizcards/index.html.erb
<h1>Listing bizcards</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bizcards.each do |bizcard| %>
  <tr>
	
	<%= bizcard.name %><br>
	<%= bizcard.bizname %>
    <td><%= link_to 'Show', bizcard %></td>
    <td><%= link_to 'Edit', edit_bizcard_path(bizcard) %></td>
    <td><%= link_to 'Destroy', bizcard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bizcard', new_bizcard_path %>

app/views/bizcards/new.html.erb
<h1>New bizcard</h1>

<%= render 'form' %>

<%= link_to 'Back', bizcards_path %>

app/views/bizcards/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_bizcard_path(@bizcard) %> |
<%= link_to 'Back', bizcards_path %>

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br />
    <%= f.number_field :friend_id %>
  </div>
  <div class="field">
    <%= f.label :create %><br />
    <%= f.text_field :create %>
  </div>
  <div class="field">
    <%= f.label :destroy %><br />
    <%= f.text_field :destroy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <tr>
    <th>User</th>
    <th>Friend</th>
    <th>Create</th>
    <th>Destroy</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friendships.each do |friendship| %>
  <tr>
    <td><%= friendship.user_id %></td>
    <td><%= friendship.friend_id %></td>
    <td><%= friendship.create %></td>
    <td><%= friendship.destroy %></td>
    <td><%= link_to 'Show', friendship %></td>
    <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
    <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @friendship.user_id %>
</p>

<p>
  <b>Friend:</b>
  <%= @friendship.friend_id %>
</p>

<p>
  <b>Create:</b>
  <%= @friendship.create %>
</p>

<p>
  <b>Destroy:</b>
  <%= @friendship.destroy %>
</p>


<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>

app/views/home/index.html.erb
<div class="row-fluid">
	<div class="span10 offset1">
		<div class="woodsection">
			
			<div class="Dashboardheader">
			My Dashboard
			</div>
<!-- Search -->			
			<div class="row-fluid">
				<div class="span12">
					<form class="search">
					<%= search_form_for @search do |f| %>
						<%= f.text_field :token_eq, :placeholder => "Enter 6 digit Pin#", :class => "searchbar" %>
						<% end %>
					</form>
					<hr>	
				</div>
			</div>			
<!-- Card Search Results -->			
			<div class="row-fluid">
				<div class="span4 offset1">
			<% if @search.conditions.empty? == false %>
			<% @users.each do |user| %>
			<div class="MYbizcardborder">
			<div class="FRbizcard">
				<div class="addmycard">
				<%= link_to friendships_path(:friend_id => user), :method => :post do %><br>
				<i class="icon-plus"></i>
				<% end %>
				</div>

				<!-- Stores CSS for current User -->
				<style>
				.FRbizcard {
					background-color: <%= "#{user.cardbackground}" %> 
				}
				</style>
				<!-- Stores CSS for current User END -->

				<div class="bizcardname">
			<%= user.full_name %>
				</div>

				<div class="bizcardcompany">
			<%= user.company %>
				</div>

				<div class="bizcardtitle">
			<%= user.title %>
				</div>
	<br>
			<% if user.twitter.blank? == false %>
				<div class="twitter">
				<a href="https://twitter.com/<%= "#{user.twitter}" %>" class="twitter-follow-button" data-show-count="false">Follow @<%= "#{user.twitter}"%></a>
				<script type="text/javascript" src="//platform.twitter.com/widgets.js">
				</script>
				</div>
			<% end %>	

			<div class="address">
			<%= user.address %>	<%= user.address2 %> <%= user.city %> <%= user.state %> <%= user.zip %>
			</div>	

			</div>
			</div>
<br>
			<% end %>	
			<% end %>
				</div>
			</div>
<!-- Card Search Results ends -->			
			
			
<!-- Search ends -->			
<!-- My Token -->
		<div class="row-fluid">
				<div class="span12">
					
					<div class="span12">
						<div class="mytoken">
					Your Pin is: <%= current_user.token %>
						</div>
					</div>
								
				</div>	
			</div>
<!-- MY Token Ends -->	
<!-- My card -->			
		<div class="row-fluid">
			<div class="span4 offset1">
				<br>
				
			
				<div class="MYbizcard">
					<div class="editmycard">
					<%= link_to edit_user_path(current_user) do %>
					<i class="icon-edit"></i>
					<% end %>
					</div>
					
					<!-- Stores CSS for current User -->
		
					<style>
					.MYbizcard {
						background-color: <%= "#{current_user.cardbackground}" %>; 
					}
					</style>
					<!-- Stores CSS for current User END -->
			
					
					<div class="bizcardname">
					<%= current_user.full_name %>
					</div>
					
					<div class="bizcardcompany">
					<%= current_user.company %>
					</div>
					
					<div class="bizcardtitle">
					<%= current_user.title %>
					</div>	
					
					<% if current_user.twitter.blank? == false %>
					<div class="twitter">
						<br>
				<a href="https://twitter.com/<%= "#{current_user.twitter}" %>" class="twitter-follow-button" data-show-count="false">Follow @<%= "#{current_user.twitter}"%></a>
					<script type="text/javascript" src="//platform.twitter.com/widgets.js">
					</script>
					</div>
					<% end %>
					
					<div class="address">
					<%= current_user.address %>	<%= current_user.address2 %> <%= current_user.city %> <%= current_user.state %> <%= current_user.zip %>
					</div>	

				</div>
			
			
			</div>
<!-- My card Ends-->
<!-- Stack of Cards Title -->
			<div class="span4 offset2">
			<br>
<!-- Stack of Cards Title Ends -->			
					
<!-- Stack of Cards -->	

<!-- Block to display self Entered Cards -->		
			<div class="bizstackwrapper">
				
							
<!-- Block to display self Entered Cards Ends -->	

<!-- Block to display friendship cards -->	
			
				<% current_user.friendships.each do |friendship| %>
			<div class="FRbizcardborder">
				<div class="bizcardstack">
					<div class="FRbizcard">
						
						<!-- Stores CSS for current User -->
						<style>
						.FRbizcard {
							background-color: #F8F7FF;
						}
						</style>
						<!-- Stores CSS for current User END -->

					<div class="cardstackremove">
					<%= link_to friendship, :method => :delete do %>
				  	<i class="icon-remove"></i>
					<% end %>
					</div>
					
					<div class="dateadded">
					<%= friendship.created_at.strftime("%a %b %d, %Y") %>
					</div>
					
					<div class="bizcardname">
					<%= friendship.friend.full_name %>
					</div>
					
					<div class="bizcardcompany">
					<%= friendship.friend.company %>
					</div>
					
					<% if friendship.friend.twitter.blank? == false %>
					<div class="twitter">
					<br>
					<a href="https://twitter.com/<%= "#{friendship.friend.twitter}" %>" class="twitter-follow-button" data-show-count="false">Follow @<%= "#{friendship.friend.twitter}"%></a>
					<script type="text/javascript" src="//platform.twitter.com/widgets.js">
					</script>
					</div>
					<% end %>
				

					</div>
				</div>
			</div>	
			<% end %>
			
			</div>	
<!-- Block to display friendship cards Ends-->
			
<!-- JQUERY for Card Movement -->				
			    <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
			    <script>
			    $(function() {
				 $( ".bizstackwrapper" ).sortable({
				            revert: false
				        });
			   
			        $( "ul, li" ).disableSelection();
			    });
			 	</script>
			</div>
			
		</div>

<!-- JQUERY for Card Movement End -->	
		
<!-- Stack of Cards End -->	


		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Netwurking</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="assets/css/bootstrap-responsive.css" rel="stylesheet">

</head>
<body>
	
	<% if user_signed_in? %>
	  Logged in as <strong><%= current_user.email %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path %> |
	  <%= link_to "Login", new_user_session_path %>
	<% end %>
	<p id="notice"><%= notice %></p>
	
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this bizcard from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




   <script>
    $(function() {
        $( "#accordion" ).accordion({
            collapsible: true, active: false
        });
    });
    </script>


<div id="accordion">
    <div class="bizcardheadereditinfo">
	<i class="icon-arrow-down"></i> Click to edit <i class="icon-arrow-down"></i>
	</div>
    <div>
        
<div class="userformwrapper">
	

<div class="row-fluid">
<div class="span2">
Name:	
</div>
<div class="span8">
<%= f.text_field :full_name, :class => "nameedit", :placeholder => "First & Last" %>
</div>
</div>

<div class="row-fluid">
<div class="span2">	
Company:
</div>
<div class="span8">
<%= f.text_field :company, :class => "companyedit", :placeholder => "Co. Name" %>
</div>
</div>

<div class="row-fluid">
<div class="span2">
Title:	
</div>		
<div class="span8">
<%= f.text_field :title, :class => "titleedit", :placeholder => "Position/Title" %>
</div>	
</div>	


<div class="row-fluid">
<div class="span2">	
Address 1:
</div>
<div class="span8">
<%= f.text_field :address, :class => "genericedit", :placeholder => "Address" %>
</div>
</div>

<div class="row-fluid">
<div class="span2">
Address 2:
</div>	
<div class="span8">
<%= f.text_field :address2, :class => "genericedit", :placeholder => "Address 2" %>
</div>
</div>

<div class="row-fluid">
<div class="span2">
City:
</div>	
<div class="span8">	
<%= f.text_field :city, :class => "cityedit", :placeholder => "City" %>
</div>
</div>

<div class="row-fluid">
<div class="span2">
State:
</div>	
<div class="span8">
<%= f.text_field :state, :class => "stateedit", :placeholder => "State" %>
</div>
</div>

<div class="row-fluid">
<div class="span2">
Zip:
</div>	
<div class="span8">	
<%= f.text_field :zip, :class => "zipedit", :placeholder => "Zip" %>
</div>
</div>

<div class="row-fluid">
<div class="span2">
@Twitter:
</div>
<div class="span8">	
<%= f.text_field :twitter, :class => "twitteredit", :placeholder => "Twitter Name" %>
</div>
</div>

<div class="actions">
<%= f.submit "Update", :class => "submitbutton"  %>
</div>


<% end %>

</div>

    </div>
</div>

app/views/users/_form2.html.erb
<div class="bizcardheaderchoosecolor">
Choose Color
</div>

<div class="colorselectwrapper">
<div class="row-fluid">
	
<div class="violetcolor">
 <%= form_for @user do |t| %>
 <%= t.hidden_field :cardbackground, :value=>"violet" %>
 <%= t.submit "Update", :class => "violetcolor" %>
<% end %>
</div>	

	<div class="bluecolor">
	 <%= form_for @user do |t| %>
	 <%= t.hidden_field :cardbackground, :value=>"#4793FA" %>
	 <%= t.submit "Update", :class =>"bluecolor" %>
	<% end %>
	</div>
	
	<div class="greencolor">
	 <%= form_for @user do |t| %>
	 <%= t.hidden_field :cardbackground, :value=>"#2CCA9E" %>
	 <%= t.submit "Update", :class =>"greencolor" %>
	<% end %>
	</div>

	<div class="graycolor">
		<%= form_for @user do |t| %>
		<%= t.hidden_field :cardbackground, :value=>"#EDEDED" %>
		<%= t.submit "Update", :class =>"graycolor" %>
		<% end %>
	</div>
	
	<div class="yellowcolor">
			<%= form_for @user do |t| %>
			<%= t.hidden_field :cardbackground, :value=>"#F4F190" %>
			<%= t.submit "Update", :class =>"yellowcolor" %>
			<% end %>
	</div>	

</div>

<div class="row-fluid">
	<div class="coolpeachcolor">
	 <%= form_for @user do |t| %>
	 <%= t.hidden_field :cardbackground, :value=>"#FFEFE7" %>
	 <%= t.submit "Update", :class => "coolpeachcolor" %>
	<% end %>
	</div>	

		<div class="coolbluecolor">
		 <%= form_for @user do |t| %>
		 <%= t.hidden_field :cardbackground, :value=>"#86C7E9" %>
		 <%= t.submit "Update", :class =>"coolbluecolor" %>
		<% end %>
		</div>

		<div class="coolgreencolor">
		 <%= form_for @user do |t| %>
		 <%= t.hidden_field :cardbackground, :value=>"#83C2BE" %>
		 <%= t.submit "Update", :class =>"coolgreencolor" %>
		<% end %>
		</div>


		<div class="coolwhitecolor">
			<%= form_for @user do |t| %>
			<%= t.hidden_field :cardbackground, :value=>"ghostwhite" %>
			<%= t.submit "Update", :class =>"coolwhitecolor" %>
			<% end %>
		</div>

		<div class="coolyellowcolor">
				<%= form_for @user do |t| %>
				<%= t.hidden_field :cardbackground, :value=>"#DFF1B5" %>
				<%= t.submit "Update", :class =>"coolyellowcolor" %>
				<% end %>
		</div>	
</div>	
</div>

app/views/users/_token.html.erb
<div class="bizcardheaderchoosetoken">
Choose Token
</div>

<%= form_for(current_user) do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this bizcard from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="userformwrapper">

<%= current_user.token %>

<% end %>

</div>

app/views/users/edit.html.erb
<div class="row-fluid">
	<div class="woodsection">
		<div class="span12">
			

			
	<div class="row-fluid">		
			
	<div class="span5 offset1">	
		<%= render "form2" %>
	</div>	

	<div class="span4 offset1">
		<div class="bizcardheadermycard">
		My Card	
		</div>	
		
		<div class="MYbizcardborder">
		<div class="MYbizcard">
			
			<!-- Stores CSS for current User -->
			<style>
			.MYbizcard {
				background-color: <%= "#{@user.cardbackground}" %> 
			}
			</style>
			<!-- Stores CSS for current User END -->
			
			<div class="bizcardname">
		<%= @user.full_name %>
			</div>
			
			<div class="bizcardcompany">
		<%= @user.company %>
			</div>
			
			<div class="bizcardtitle">
		<%= @user.title %>
			</div>
<br>
		<% if @user.twitter.blank? == false %>
			<div class="twitter">
			<a href="https://twitter.com/<%= "#{@user.twitter}" %>" class="twitter-follow-button" data-show-count="false">Follow @<%= "#{@user.twitter}"%></a>
			<script type="text/javascript" src="//platform.twitter.com/widgets.js">
			</script>
			</div>
		<% end %>	
		
		<div class="address">
					<%= current_user.address %>	<%= current_user.address2 %> <%= current_user.city %> <%= current_user.state %> <%= current_user.zip %>
		</div>	
				
		</div>
		</div>
	
	</div>
	
	</div>
	
	<div class="row-fluid">
		<div class="span10 offset1">
		<%= render "form" %>
		</div>
	</div>
		
		</div>
	</div>
</div>	

app/views/users/index.html.erb
<div class="row-fluid">
	<div class="woodsection">
		<div class="span12">
			
				<form class="search">
				<%= search_form_for @search do |f| %>
				 <input type="text" class="search-query" placeholder="Search"><br>
				<%= f.text_field :token_start %>
				<div class="actions">
				<%= f.submit %>
				</div>

			
			
<% @users.each do |user| %>
	<%= user.full_name %><br>
	<%= link_to "Add Card", friendships_path(:friend_id => user), :method => :post %><br>
	<% end %>
	
		<% end %>
		</form>
	
</div>	
</div>	
</div>	

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row-fluid">
	<div class="woodsection">
		<div class="span12">
			
	<div class="row-fluid">
	<div class="span4 offset1">
		<br>
		<div class="bizcardheader">
		My Card	
		</div>	
		
		<div class="bizcard">
			
			<!-- Stores CSS for current User -->
			<style>
			.bizcard {
				background-color: <%= "#{@user.cardbackground}" %> 
			}
			</style>
			<!-- Stores CSS for current User END -->
			
			<div class="bizcardname">
		<%= best_in_place @user, :full_name %>
			</div>
			<div class="bizcardcompany">
		Company
<br>
			<%= best_in_place @user, :cardbackground, :type => :input %>
			</div>
		</div>
	
	</div>
	
</div>
</div>
</div>	
	